name: WeKeyPedia
markdown: redcarpet
highlighter: pygments
collections:
  - projects
  - members
  - talks
  - workshops
defaults:
  - scope:
      type: projects
    values:
      importance: "2 - side projects"
